version: '2.3'
networks:
  postgres:
    driver: bridge
    ipam:
      config:
        - subnet: 172.4.0.0/16
  redis-network:
    driver: bridge

volumes:
  pgdata:
  redis:
  redis-config:

services:
  # postgres:
  #   # container_name: postgres_container
  #   image: postgres:13.3
  #   environment:
  #     POSTGRES_DB: "BDAAA"
  #     POSTGRES_USER: "aaa"
  #     POSTGRES_PASSWORD: "1234"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data/
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - postgres

  # pgadmin:
  #   # container_name: pgadmin_container
  #   image: dpage/pgadmin4:5.7
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "test@mail.ru"
  #     PGADMIN_DEFAULT_PASSWORD: "1234"
  #     PGADMIN_CONFIG_SERVER_MODE: "False"
  #   volumes:
  #     - ./private/var/lib/pgadmin:/var/lib/pgadmin
  #   ports:
  #     - "8080:80"
  #   restart: unless-stopped
  #   networks:
  #     - postgres

  redis:
    image: redis:latest
    restart: always
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - postgres

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    networks:
      - postgres
    depends_on:
      - redis